version: "3.3"

services:
  web:
    build: Reviews_Api/
    ports:
      - "3001:3001"
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'reviews_api'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      
volumes:
  db_data: 
